language: node_js

node_js: node

cache:
  directories:
    - node_modules

script:
  - npm install
  - npm run build
  - npm run build-storybook

jobs:
  include:
    - stage: release
      node_js: lts/*
      deploy:
        - provider: pages
          skip_cleanup: true
          github_token: $GITHUB_TOKEN
          local_dir: storybook-static
          on:
            branch: main
